# ROBOT : 'iiwa' 
# TASK  : end-effector position tracking task


# MPC & sim parameters
ctrl_freq: 1000         # Control frequency
RICCATI: False 


# General
SOLVER: 'grg' # 'fddp'
dt: 0.04                                             # OCP integration step 
N_h: 5                                              # Horizon length in nodes
maxiter: 8                                           # Max number of iterations 
solver_termination_tolerance: 0.0001                 # Tolerance on KKT residual 
use_filter_line_search: True 
filter_size: 5
q0: [0., 1.0471975511965976, 0., -1.1344640137963142, 0.2,  0.7853981633974483, 0.]               # Initial robot joint configuration
dq0: [0.,0.,0.,0.,0.,0.,0.]                         # Initial robot joint velocity


T_REACH: 0.
T_CIRCLE: 2.

# Cost function composition (a.k.a which terms will be actually used in the OCP)
# to select from the list : 'stateReg', 'ctrlReg', 'ctrlRegGrav', 'stateLim', 'ctrlLim'
#                           'force', 'friction', 'translation', 'velocity', 'placement'
WHICH_COSTS: ['translation', 'ctrlRegGrav', 'stateReg'] 

# Cost function weights and activations
 # 'stateReg' : state regularization  
stateRegWeights: [20., 20., 20., 10., 10., 10, 10., 2., 2., 2., 2., 2., 2., 2.]
stateRegWeight: 0.01
stateRegWeightTerminal: 0.01
stateRegRef: 'DEFAULT'  # 'DEFAULT' = [q0, v0]


 # 'ctrlReg', 'ctrlRegGrav' : torque regularization 
ctrlRegGravWeights: [1., 1., 1., 1., 1., 1., 1.]
ctrlRegGravWeight: 0.0001
ctrlRegGravWeightTerminal: 0.0001


 # 'translation' : end-effector frame translation 
frameTranslationWeights:  [1., 1., 1.] 
frameTranslationWeight: 1.
frameTranslationWeightTerminal: 10. 
frameTranslationRef: [0.6, 0., 0.155] 
frameTranslationFrameName: 'contact'  


# armature
armature: [0., 0., 0., 0., 0., 0., 0.]
